#!/bin/bash                                                                                                                                                                                   
#PBS -l mem=120gb,nodes=1:ppn=1,walltime=72:00:00                                                                                                                                             
#PBS -A hirschc1                                                                                                                                                                              
#PBS -m abe                                                                                                                                                                                   
#PBS -o /home/hirschc1/oconnorc/OandE                                                                                                                                                         
#PBS -e /home/hirschc1/oconnorc/OandE                                                                                                                                                         
#PBS -M oconnorc@umn.edu                                                                                                                                                                      
#PBS -q mangi                                                                                                                                                                                 
#PBS -N platy_process                                                                                                                                                                            

newgrp - hirschc1                                                                                                                                                                            

#job to run samtools filter and sort using gnu parallel                                                                                                                                       

#go here: https://www.msi.umn.edu/support/faq/how-can-i-use-gnu-parallel-Vun-lot-commands-parallel                                                                                            

#load needed modules                                                                                                                                                                          
module load parallel
module load gatk/4.1.2
module load java/jdk1.8.0_171

cd /home/hirschc1/oconnorc/software/GenomeAnalysisTK-3.8-1-0-gf15c1c3ef

java -cp GenomeAnalysisTK.jar org.broadinstitute.gatk.tools.CatVariants -R /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr1.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr1.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr1.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr1.D_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr2.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr2.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr2.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr3.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr3.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr3.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr4.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr4.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr4.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr5.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr5.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr5.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr6.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr6.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr7.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr7.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr8.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr8.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr9.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr9.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr10.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_chr10.B_platy.vcf -out /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_allchr_gene1kb_platy.vcf

java -cp GenomeAnalysisTK.jar org.broadinstitute.gatk.tools.CatVariants -R /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr1.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr1.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr1.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr1.D_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr2.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr2.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr2.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr3.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr3.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr3.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr4.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr4.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr4.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr5.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr5.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr5.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr6.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr6.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr7.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr7.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr8.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr8.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr8.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr9.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr9.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr10.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_chr10.B_platy.vcf -out /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_allchr_gene1kb_platy.vcf

java -cp GenomeAnalysisTK.jar org.broadinstitute.gatk.tools.CatVariants -R /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr1.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr1.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr1.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr1.D_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr2.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr2.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr2.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr3.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr3.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr3.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr4.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr4.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr4.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr5.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr5.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr5.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr6.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr6.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr7.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr7.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr8.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr8.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr9.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr9.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr10.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_chr10.B_platy.vcf -out /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_allchr_gene1kb_platy.vcf

java -cp GenomeAnalysisTK.jar org.broadinstitute.gatk.tools.CatVariants -R /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr1.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr1.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr1.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr1.D_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr2.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr2.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr2.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr3.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr3.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr3.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr4.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr4.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr4.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr5.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr5.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr5.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr6.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr6.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr7.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr7.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr8.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr8.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr8.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr9.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr9.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr10.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_chr10.B_platy.vcf -out /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_allchr_gene1kb_platy.vcf

java -cp GenomeAnalysisTK.jar org.broadinstitute.gatk.tools.CatVariants -R /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr1.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr1.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr1.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr1.D_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr2.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr2.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr2.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr3.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr3.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr3.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr4.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr4.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr4.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr5.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr5.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr5.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr6.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr6.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr7.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr7.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr8.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr8.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr8.C_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr9.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr9.B_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr10.A_platy.vcf -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_chr10.B_platy.vcf -out /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_allchr_gene1kb_platy.vcf

cd /home/hirschc1/oconnorc/platypus_output/

gatk SelectVariants -V /home/hirschc1/oconnorc/maize_refs/B73_chr1-10.fasta -select-type INDEL -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_B73v4_allchr_gene1kb_platy.vcf --min-indel-size 2 -O /home/hirschc1/oconnorc/platypus_output/WiDiv509_B73v4_allchr_platy_indels.vcf

gatk SelectVariants -V /home/hirschc1/oconnorc/maize_refs/Mo17_chr1-10.fasta -select-type INDEL -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_Mo17_allchr_gene1kb_platy.vcf --min-indel-size 2 -O /home/hirschc1/oconnorc/platypus_output/WiDiv509_Mo17_allchr_platy_indels.vcf

gatk SelectVariants -V /home/hirschc1/oconnorc/maize_refs/PH207_chr1-10.fasta -select-type INDEL -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PH207_allchr_gene1kb_platy.vcf --min-indel-size 2 -O /home/hirschc1/oconnorc/platypus_output/WiDiv509_PH207_allchr_platy_indels.vcf

gatk SelectVariants -V /home/hirschc1/oconnorc/maize_refs/PHB47_chr1-10.fasta -select-type INDEL -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_PHB47_allchr_gene1kb_platy.vcf --min-indel-size 2 -O /home/hirschc1/oconnorc/platypus_output/WiDiv509_PHB47_allchr_platy_indels.vcf

gatk SelectVariants -V /home/hirschc1/oconnorc/maize_refs/W22_chr1-10.fasta -select-type INDEL -V /home/hirschc1/oconnorc/platypus_output/WiDiv509_all_W22v12_allchr_gene1kb_platy.vcf --min-indel-size 2 -O /home/hirschc1/oconnorc/platypus_output/WiDiv509_W22v12_allchr_platy_indels.vcf

#cd /home/hirschc1/oconnorc/freebayes_output
#fix freebayes indel call files 
#re-do PHB47 because reference genome for indel SelectVariants is incorrect 
#gatk SelectVariants -V /home/hirschc1/oconnorc/maize_refs/PHB47_chr1-10.fasta -select-type INDEL --sample-name /home/hirschc1/oconnorc/freebayes_output/PHB47_sample_names.args -V /home/hirschc1/oconnorc/freebayes_output/WiDiv509_PHB47_allchr_gene1kb.vcf --min-indel-size 2 -O /home/hirschc1/oconnorc/freebayes_output/WiDiv508_PHB47_allchr_indels.vcf
#gatk SelectVariants -V /home/hirschc1/oconnorc/maize_refs/W22_chr1-10.fasta -select-type INDEL --sample-name /home/hirschc1/oconnorc/freebayes_output/W22_sample_names.args -V /home/hirschc1/oconnorc/freebayes_output/WiDiv509_W22v12_allchr_gene1kb_run2.vcf --min-indel-size 2 -O /home/hirschc1/oconnorc/freebayes_output/WiDiv508_W22v12_allchr_indels.vcf   

#keep all 509 genotypes for all samples 
#gatk SelectVariants -V /home/hirschc1/oconnorc/maize_refs/B73_chr1-10.fasta -select-type INDEL --sample-name /home/hirschc1/oconnorc/freebayes_output/WiDiv509_samplenames.args -V /home/hirschc1/oconnorc/freebayes_output/WiDiv512_B73_allchr_gene1kb.vcf --min-indel-size 2 -O /home/hirschc1/oconnorc/freebayes_output/WiDiv509_Mo17_fb_allchr_indels.vcf                                 
#gatk SelectVariants -V /home/hirschc1/oconnorc/maize_refs/Mo17_chr1-10.fasta -select-type INDEL --sample-name /home/hirschc1/oconnorc/freebayes_output/WiDiv509_samplenames.args -V /home/hirschc1/oconnorc/freebayes_output/WiDiv512_Mo17_allchr_gene1kb.vcf --min-indel-size 2 -O /home/hirschc1/oconnorc/freebayes_output/WiDiv509_Mo17_fb_allchr_indels.vcf                                 
#gatk SelectVariants -V /home/hirschc1/oconnorc/maize_refs/PHB47_chr1-10.fasta -select-type INDEL --sample-name /home/hirschc1/oconnorc/freebayes_output/WiDiv509_samplenames.args -V /home/hirschc1/oconnorc/freebayes_output/WiDiv509_PHB47_allchr_gene1kb.vcf --min-indel-size 2 -O /home/hirschc1/oconnorc/freebayes_output/WiDiv509_PHB47_fb_allchr_indels.vcf
#gatk SelectVariants -V /home/hirschc1/oconnorc/maize_refs/PH207_chr1-10.fasta -select-type INDEL --sample-name /home/hirschc1/oconnorc/freebayes_output/WiDiv509_samplenames.args -V /home/hirschc1/oconnorc/freebayes_output/WiDiv510_PH207_allchr_gene1kb.vcf --min-indel-size 2 -O /home/hirschc1/oconnorc/freebayes_output/WiDiv509_PH207_fb_allchr_indels.vcf                                                                                                                     
#gatk SelectVariants -V /home/hirschc1/oconnorc/maize_refs/W22_chr1-10.fasta -select-type INDEL --sample-name /home/hirschc1/oconnorc/freebayes_output/WiDiv509_samplenames.args -V /home/hirschc1/oconnorc/freebayes_output/WiDiv509_W22v12_allchr_gene1kb.vcf --min-indel-size 2 -O /home/hirschc1/oconnorc/freebayes_output/WiDiv509_W22v12_fb_allchr_indels.vcf                                                                                                                       

#re-do SNP filters 

#gatk SelectVariants -V /home/hirschc1/oconnorc/maize_refs/B73_chr1-10.fasta -select-type SNP --sample-name /home/hirschc1/oconnorc/freebayes_output/WiDiv509_samplenames.args -V /home/hirschc1/oconnorc/freebayes_output/WiDiv512_B73_allchr_gene1kb.vcf -O /home/hirschc1/oconnorc/freebayes_output/WiDiv509_B73v4_allchr_SNPs.vcf                                                        
#gatk VariantFiltration -V /home/hirschc1/oconnorc/maize_refs/B73_chr1-10.fasta -V /home/hirschc1/oconnorc/freebayes_output/WiDiv509_B73v4_allchr_SNPs.vcf --filter-expression "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0" --filter-name "GATK_snp_filter" -O /home/hirschc1/oconnorc/freebayes_output/WiDiv509_B73v4_allchr_filtered_SNPs.vcf 
#/home/hirschc1/oconnorc/software/vcftools_0.1.13/bin/vcftools --vcf /home/hirschc1/oconnorc/freebayes_output/WiDiv509_B73v4_allchr_filtered_SNPs.vcf  --Vemove-filtered-all --max-missing 0.10 --mac 50 --minQ 30 --Vecode --Vecode-INFO-all --out /home/hirschc1/oconnorc/freebayes_output/WiDiv509_B73v4_allchr_SNPS_maxmiss0.10                                                               

#gatk SelectVariants -V /home/hirschc1/oconnorc/maize_refs/Mo17_chr1-10.fasta -select-type SNP --sample-name /home/hirschc1/oconnorc/freebayes_output/WiDiv509_samplenames.args -V /home/hirschc1/oconnorc/freebayes_output/WiDiv512_Mo17_allchr_gene1kb.vcf -O /home/hirschc1/oconnorc/freebayes_output/WiDiv509_Mo17_allchr_SNPs.vcf                                                        
#gatk VariantFiltration -V /home/hirschc1/oconnorc/maize_refs/Mo17_chr1-10.fasta -V /home/hirschc1/oconnorc/freebayes_output/WiDiv509_Mo17_allchr_SNPs.vcf --filter-expression "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0" --filter-name "GATK_snp_filter" -O /home/hirschc1/oconnorc/freebayes_output/WiDiv509_Mo17_allchr_filtered_SNPs.vcf 
#/home/hirschc1/oconnorc/software/vcftools_0.1.13/bin/vcftools --vcf /home/hirschc1/oconnorc/freebayes_output/WiDiv509_Mo17_allchr_filtered_SNPs.vcf  --Vemove-filtered-all --max-missing 0.10 --mac 50 --minQ 30 --Vecode --Vecode-INFO-all --out /home/hirschc1/oconnorc/freebayes_output/WiDiv509_Mo17_allchr_SNPS_maxmiss0.10                                                               

#gatk SelectVariants -V /home/hirschc1/oconnorc/maize_refs/PHB47_chr1-10.fasta -select-type SNP --sample-name /home/hirschc1/oconnorc/freebayes_output/WiDiv509_samplenames.args -V /home/hirschc1/oconnorc/freebayes_output/WiDiv509_PHB47_allchr_gene1kb.vcf -O /home/hirschc1/oconnorc/freebayes_output/WiDiv509_PHB47_allchr_SNPs.vcf
#gatk VariantFiltration -V /home/hirschc1/oconnorc/maize_refs/PHB47_chr1-10.fasta -V /home/hirschc1/oconnorc/freebayes_output/WiDiv509_PHB47_allchr_SNPs.vcf --filter-expression "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0" --filter-name "GATK_snp_filter" -O /home/hirschc1/oconnorc/freebayes_output/WiDiv509_PHB47_allchr_filtered_SNPs.vcf
#/home/hirschc1/oconnorc/software/vcftools_0.1.13/bin/vcftools --vcf /home/hirschc1/oconnorc/freebayes_output/WiDiv509_PHB47_allchr_filtered_SNPs.vcf  --Vemove-filtered-all --max-missing 0.10 --mac 50 --minQ 30 --Vecode --Vecode-INFO-all --out /home/hirschc1/oconnorc/freebayes_output/WiDiv509_PHB47_allchr_SNPS_maxmiss0.10

#gatk SelectVariants -V /home/hirschc1/oconnorc/maize_refs/PH207_chr1-10.fasta -select-type SNP --sample-name /home/hirschc1/oconnorc/freebayes_output/WiDiv509_samplenames.args -V /home/hirschc1/oconnorc/freebayes_output/WiDiv510_PH207_allchr_gene1kb.vcf -O ~/freebayes_output/WiDiv509_PH207_allchr_SNPs.vcf                                                                                                                                            
#gatk VariantFiltration -V /home/hirschc1/oconnorc/maize_refs/PH207_chr1-10.fasta -V /home/hirschc1/oconnorc/freebayes_output/WiDiv509_PH207_allchr_SNPs.vcf --filter-expression "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0" --filter-name "GATK_snp_filter" -O /home/hirschc1/oconnorc/freebayes_output/WiDiv509_PH207_allchr_filtered_SNPs.vcf                                                                      
#/home/hirschc1/oconnorc/software/vcftools_0.1.13/bin/vcftools --vcf /home/hirschc1/oconnorc/freebayes_output/WiDiv509_PH207_allchr_filtered_SNPs.vcf  --Vemove-filtered-all --max-missing 0.10 --mac 50 --minQ 30 --Vecode --Vecode-INFO-all --out ~/freebayes_output/WiDiv509_PH207_allchr_SNPS_maxmiss0.10                                                                                                                          

#gatk SelectVariants -V /home/hirschc1/oconnorc/maize_refs/W22_chr1-10.fasta -select-type SNP --sample-name /home/hirschc1/oconnorc/freebayes_output/WiDiv509_samplenames.args -V /home/hirschc1/oconnorc/freebayes_output/WiDiv509_W22v12_allchr_gene1kb_run2.vcf -O ~/freebayes_output/WiDiv509_W22v12_allchr_SNPs.vcf                                                                                                                                              
#gatk VariantFiltration -V /home/hirschc1/oconnorc/maize_refs/W22_chr1-10.fasta -V /home/hirschc1/oconnorc/freebayes_output/WiDiv509_W22v12_allchr_SNPs.vcf --filter-expression "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0" --filter-name "GATK_snp_filter" -O /home/hirschc1/oconnorc/freebayes_output/WiDiv509_W22v12_allchr_filtered_SNPs.vcf                                                                      
#/home/hirschc1/oconnorc/software/vcftools_0.1.13/bin/vcftools --vcf /home/hirschc1/oconnorc/freebayes_output/WiDiv509_W22v12_allchr_filtered_SNPs.vcf  --Vemove-filtered-all --max-missing 0.10 --mac 50 --minQ 30 --Vecode --Vecode-INFO-all --out ~/freebayes_output/WiDiv509_W22v12_allchr_SNPS_maxmiss0.10                                                                                                                        

#re-do W22
#gatk SelectVariants -V /home/hirschc1/oconnorc/maize_refs/W22_chr1-10.fasta -select-type SNP --sample-name /home/hirschc1/oconnorc/freebayes_output/W22_sample_names.args -V /home/hirschc1/oconnorc/freebayes_output/WiDiv509_W22v12_allchr_gene1kb_run2.vcf -O /home/hirschc1/oconnorc/freebayes_output/WiDiv508_W22v12_allchr_SNPs.vcf                                                                                                                                              
#gatk VariantFiltration -V /home/hirschc1/oconnorc/maize_refs/W22_chr1-10.fasta -V /home/hirschc1/oconnorc/freebayes_output/WiDiv508_W22v12_allchr_SNPs.vcf --filter-expression "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0" --filter-name "GATK_snp_filter" -O /home/hirschc1/oconnorc/freebayes_output/WiDiv508_W22v12_allchr_filtered_SNPs.vcf                                                                      
#/home/hirschc1/oconnorc/software/vcftools_0.1.13/bin/vcftools --vcf /home/hirschc1/oconnorc/freebayes_output/WiDiv508_W22v12_allchr_filtered_SNPs.vcf  --Vemove-filtered-all --max-missing 0.10 --mac 50 --minQ 30 --Vecode --Vecode-INFO-all --out /home/hirschc1/oconnorc/freebayes_output/WiDiv508_W22v12_allchr_SNPS_maxmiss0.10 


#end of script 
